AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  StripeWebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: StripeWebhookFunction
      Handler: com.kaplansoftware.imweb.StripeWebhookHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          livemode: false
          mongoConnectionString: mongodb://imwebdev:Passw0rd@ds153314.mlab.com:53314/imweb-dev?retryWrites=false
          stripeSK: sk_test_klJynNOHotjgLRtt3wRUKLxw
          cryptoSalt: 154a6f0bed1c829c619b700d1307d576

      Events:
        StripeWebhook:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stripe
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StripeWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  StripeWebhookFunction:
    Description: "Stripe Webhook Handler Lambda Function ARN"
    Value: !GetAtt StripeWebhookFunction.Arn
  StripeWebhookFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt StripeWebhookFunctionRole.Arn
